-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
	gender,
	sum(purchase_amount)
FROM
	customer
GROUP BY
	gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
	customer_id,
	purchase_amount
FROM
	customer
WHERE
	discount_applied = 'Yes'
	AND purchase_amount > (
		SELECT
			avg(purchase_amount)
		FROM
			customer
	)
GROUP BY
	customer_id,
	purchase_amount
ORDER BY
	1,
	2;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
	item_purchased,
	ROUND(AVG(review_rating)::NUMERIC, 2) AS average_rating
FROM
	customer
GROUP BY
	item_purchased
ORDER BY
	average_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
	shipping_type,
	round(AVG(purchase_amount)::numeric, 2)
FROM
	customer
WHERE
	shipping_type IN ('Express', 'Standard')
GROUP BY
	shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
	subscription_status,
	count(customer_id) AS total_customers,
	round(avg(purchase_amount)::numeric, 2) AS avg_spend,
	sum(purchase_amount) AS total_revenue
FROM
	customer
GROUP BY
	subscription_status
ORDER BY
	total_revenue DESC,
	avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
	item_purchased,
	round(
		100 * sum(
			CASE
				WHEN discount_applied = 'Yes' THEN 1
				ELSE 0
			END
		) / count(item_purchased)
	) AS discount_percentage
FROM
	customer
GROUP BY
	item_purchased
ORDER BY
	discount_percentage DESC
LIMIT
	5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
	customer_segment,
	count(*) as total_customers
FROM
	(
		SELECT
			customer_id,
			previous_purchases,
			CASE
				WHEN previous_purchases = 1 THEN 'New'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal'
			END AS customer_segment
		FROM
			customer
		GROUP BY
			customer_id,
			previous_purchases
	) AS segments
GROUP BY
	customer_segment
ORDER BY total_customers DESC;

-----------------------------------------------------------------------------

WITH
	customer_type AS (
		SELECT
			customer_id,
			previous_purchases,
			CASE
				WHEN previous_purchases = 1 THEN 'New'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal'
			END AS customer_segment
		FROM
			customer
	)
SELECT
	customer_segment,
	count(*) AS counts
FROM
	customer_type
GROUP BY
	customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH
	item_counts AS (
		SELECT
			category,
			item_purchased,
			count(*) AS total_orders,
			row_number() OVER (
				PARTITION BY
					category
				ORDER BY
					count(*) DESC
			) AS item_rank
		FROM
			customer
		GROUP BY
			category,
			item_purchased
		ORDER BY
			category,
			item_rank
	)
SELECT
	item_rank,
	category,
	item_purchased,
	total_orders
FROM
	item_counts
WHERE
	item_rank <= 3;

-----------------------------------------------------------------------------

SELECT
	*
FROM
	(
		SELECT
			category,
			ROW_NUMBER() OVER (
				PARTITION BY
					category
				ORDER BY
					count(*) DESC
			) AS item_rank,
			item_purchased,
			count(*) AS total_orders
		FROM
			customer
		GROUP BY
			category,
			item_purchased
		ORDER BY
			category,
			item_rank
	)
WHERE
	item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	subscription_status,
	count(*)
FROM
	customer
WHERE
	previous_purchases > 5
GROUP BY
	subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT
	age_group,
	count(*),
	sum(purchase_amount) AS total_revenue,
	round(100 * sum(purchase_amount) / sum(sum(purchase_amount)) OVER (), 2) AS revenue_percentage
FROM
	customer
GROUP BY
	age_group
ORDER BY
	total_revenue DESC;

select * from customer;